# ### ADMIN PARA TRANSACCIONES ESPECIALES

# POST http://localhost:3000/authenticate HTTP/1.1
# content-type: application/json

# {
#     "email":"admin@example.com.co",
#     "password":"123456789"
# }

# ### REGISTRO DE USUARIOS

# POST http://localhost:3000/users HTTP/1.1
# content-type: application/json

# { "user": 
#    {
#       "name":"Juan",
#       "last_name":"Rodriguez",
#       "email":"juancaropu123@gmail.com",
#       "password":"123456789",
#       "password_confirmation":"123456789",
#       "role_id":"1",
#       "career_id":"1"
#    }
# }

# ### INICIO DE SESIÓN

# POST http://localhost:3000/authenticate HTTP/1.1
# content-type: application/json

# {
#     "email":"jucrodriguezpu@unal.edu.co",
#     "password":"987654321"
# }

# ### CREAR CARRERAS

# POST http://localhost:3000/careers HTTP/1.1
# Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE1NTI0MTE0ODV9.Zkh4GeBThGCBwgl5aoz_gHRYGpzYq0m8MqIPvBDixKs
# content-type: application/json

# { 
#     "name":"Ciencias de la Computación"
# }

# ### CREAR MATERIAS => Éstas tendrán guardado por defecto el primer profesor que creo la materia, 
#                       PERO DEBE AÚN ASIGNARLE LA MATERIA

# POST http://localhost:3000/subjects HTTP/1.1
# Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE1NTI0MTM3MjB9.8ZedH7y2H6hwyTYPqte8sq8tJh7NbPU_9MfLczFk720
# content-type: application/json

# { 
#     "name":"Programación de Computadores C++",
#     "summary":"Ésta es una materia sobre programación básica de computadores usando el lenguaje C++",
#     "user_id": 3
# }

# ### ASIGNAR MATERIAS

# POST http://localhost:3000/subjects HTTP/1.1
# Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE1NTI0MTM3MjB9.8ZedH7y2H6hwyTYPqte8sq8tJh7NbPU_9MfLczFk720
# content-type: application/json

# { 
#     "name":"%Programación Ruby%",
#     "user_id": 3
# }

# ###CREAR ARTÍCULOS

# POST http://localhost:3000/articles HTTP/1.1
# Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE1NTIxNjczNjZ9.GT9qvQvbytVOzUIVXJYd0B-RmNi8U4CjlJOsH9W-HWc
# content-type: application/json

# { 
#     "title":"Primera generación de Ciencias de la Computación ingresa a la U.N.",
#     "body":"El programa tendrá como base una sólida formación en la investigación, lo que le permitirá al estudiante ser un desarrollador de nueva tecnología, más que una adaptador, explicó el vicedecano académico de la Facultad de Ciencias, Giovanny Garavito Cárdenas.",
#     "visits_count": 0,
#     "url":"http://agenciadenoticias.unal.edu.co/detalle/article/primera-generacion-de-ciencias-de-la-computacion-ingresa-a-la-un.html",
#     "user_id": 2
# }

# ### BUSQUEDA DE PROFESORES POR NOMBRE O APELLIDO

# /// VERSIÓN 1
# POST http://localhost:3000/professorsname HTTP/1.1
# content-type: application/json

# { 
#     "last_name":"%Martínez%"
# }

# /// VERSIÓN 2
# POST http://localhost:3000/professorsname HTTP/1.1
# content-type: application/json

# { 
#     "name":"%Iván%"
# }

# /// VERSIÓN 3
# POST http://localhost:3000/professorsname HTTP/1.1
# content-type: application/json

# { 
#     "name":"%Yesid%",
#     "last_name":"%Castellanos%"
# }

# ### BUSQUEDA DE MATERIAS POR NOMBRE

# POST http://localhost:3000/subjectsname HTTP/1.1
# content-type: application/json

# { 
#     "name":"%Ruby%"
# }


# ### RECUPERACION DE CONTRASEÑA
# ## PASO 1 => Envio de correo con token ( Se construye una URL así http://#{base_url}/ChangePassword/#{@user.email}/#{@user.reset_password_token} )

# POST http://localhost:3000/passwords/forgot
# content-type: application/json

# {
#     "email":"jucrodriguezpu@unal.edu.co"
# }

# ## PASO 2 => Ingresar para modificar contraseña

# POST http://localhost:3000/passwords/reset
# content-type: application/json

# {
#     "email":"jucrodriguezpu@unal.edu.co",
#     "password": "987654321",
#     "token": "3b7324b7bdec6e91a9c9"
# }
