production:
  adapter: postgresql
  url: postgres://localhost/pgac_prod
  channel_prefix: CableChat_production

development:
  adapter: postgresql
  url: postgres://localhost/pgac_dev

test:
  adapter: postgresql
  url: postgres://localhost/pgac_test
  channel_prefix: Learnify_Backv3_production
